/*
 * Stoatworks Labs - About window data for plotter.
 *
 * PROVISIONAL HAND COPY, adapted from galvo's generated header on 2026-09-24.
 * The real one is generated by stoatworks-backend/scripts/sync-about.py from
 * the website's projects.json once the project is registered there; until
 * then this carries the same facts by hand, with guide="" because no user
 * guide exists yet.
 *
 * `version` here is a fallback read from this repo's own manifest at sync
 * time. Anything with a build step injects the real one at build time and
 * overrides this.
 */
#pragma once

namespace stoatworks::about
{
    inline constexpr auto name = "plotter";
    inline constexpr auto slug = "plotter";
    inline constexpr auto hook = "A pen plotter drawing the clip, for Resolume";
    inline constexpr auto licence = "MIT";
    inline constexpr auto guide = "";
    inline constexpr auto page = "https://stoatworks-labs.com/software/plotter/";
    inline constexpr auto repo = "https://github.com/stoatworks-labs/plotter";
    inline constexpr auto versionFallback = "v0.1.0";

    inline constexpr auto org = "Stoatworks Labs";
    inline constexpr auto home = "https://stoatworks-labs.com";
    inline constexpr auto tagline = "Open tools for the people who run the show.";

    /* The canonical funding links, matching FUNDING.yml and the support footer. */
    struct Link { const char* name; const char* url; };
    inline constexpr Link funding[] = {
        { "GitHub Sponsors", "https://github.com/sponsors/stoatworks-labs" },
        { "Ko-fi", "https://ko-fi.com/stoatworkslabs" },
        { "Patreon", "https://patreon.com/StoatworksLabs" },
        { "Liberapay", "https://liberapay.com/stoatworks-labs" },
    };
}
